name: CICD

on:
  push:
    branches: [ deploy-to-ec2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Copy JAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} target/explorer-0.0.1-SNAPSHOT.jar ec2-user@ec2-35-153-136-5.compute-1.amazonaws.com:~
      - name: Start JAR on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-35-153-136-5.compute-1.amazonaws.com "nohup java -jar explorer-0.0.1-SNAPSHOT.jar > output.log &"
